# Generated by Django 4.1.7 on 2023-05-02 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("News_Portal", "0002_subscribers"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscribers",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="News_Portal.category",
            ),
        ),
    ]
